//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cnfConfiguracion
    {
        public int codConfig { get; set; }
        public Nullable<System.Guid> codCuenta { get; set; }
        public Nullable<short> codplaza { get; set; }
        public Nullable<short> codEmpresa { get; set; }
        public string seccion { get; set; }
        public string unidad { get; set; }
        public string valor { get; set; }
    }
}
