//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cnfCuentas
    {
        public System.Guid codCuenta { get; set; }
        public string cuenta { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
        public short codPlaza { get; set; }
        public string tipo { get; set; }
        public string password { get; set; }
        public Nullable<short> perfilSonido { get; set; }
        public Nullable<System.DateTime> fechaCadPass { get; set; }
    }
}
