//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cnfPermisosxModulo
    {
        public short codPermiso { get; set; }
        public string permiso { get; set; }
        public int codModulo { get; set; }
        public string modulo { get; set; }
        public string nombreMenu { get; set; }
    }
}
