//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cnfRestriccionesxCuenta
    {
        public int codRestriccionxCuenta { get; set; }
        public short codRestriccion { get; set; }
        public System.Guid codCuenta { get; set; }
        public System.Guid codCuentaDirecta { get; set; }
        public System.DateTime FechaAlta { get; set; }
    }
}
