//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ConfigEntities : DbContext
    {
        public ConfigEntities()
            : base("name=ConfigEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cnfCuentas> cnfCuentas { get; set; }
        public DbSet<cnfEmpresasxCuenta> cnfEmpresasxCuenta { get; set; }
        public DbSet<cnfModulos> cnfModulos { get; set; }
        public DbSet<cnfModulosxCuenta> cnfModulosxCuenta { get; set; }
        public DbSet<cnfPermisos> cnfPermisos { get; set; }
        public DbSet<cnfPermisosxCuenta> cnfPermisosxCuenta { get; set; }
        public DbSet<cnfPermisosxModulo> cnfPermisosxModulo { get; set; }
        public DbSet<cnfPlazasxCuenta> cnfPlazasxCuenta { get; set; }
        public DbSet<cnfRestricciones> cnfRestricciones { get; set; }
        public DbSet<cnfRestriccionesxCuenta> cnfRestriccionesxCuenta { get; set; }
        public DbSet<cnfTiposCliente> cnfTiposCliente { get; set; }
        public DbSet<cnfTiposPlaza> cnfTiposPlaza { get; set; }
        public DbSet<cnfTiposRed> cnfTiposRed { get; set; }
        public DbSet<cnfConfiguracion> cnfConfiguracion { get; set; }
    
        public virtual int secActivaCuenta(string cuenta)
        {
            var cuentaParameter = cuenta != null ?
                new ObjectParameter("cuenta", cuenta) :
                new ObjectParameter("cuenta", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("secActivaCuenta", cuentaParameter);
        }
    
        public virtual int secDesactivaMe()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("secDesactivaMe");
        }
    }
}
