//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaLog
    {
        public long id { get; set; }
        public System.DateTime ftick { get; set; }
        public string xmlIn { get; set; }
        public string xmlOut { get; set; }
        public string proceso { get; set; }
        public string observaciones { get; set; }
    }
}
