//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class geoPlazas
    {
        public int codgeoplaza { get; set; }
        public short codplaza { get; set; }
        public Nullable<float> lon { get; set; }
        public Nullable<float> lat { get; set; }
        public Nullable<short> accuracy { get; set; }
        public string contesta { get; set; }
        public System.DateTime ftick { get; set; }
        public string direccion { get; set; }
        public Nullable<short> codpais { get; set; }
    }
}
