//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pnlExpediciones
    {
        public long id { get; set; }
        public short codplaza_org { get; set; }
        public int codexp { get; set; }
        public System.DateTime fechaPenaliza { get; set; }
        public Nullable<System.DateTime> FPEntrega { get; set; }
        public byte codtipo { get; set; }
        public Nullable<short> codconcepto { get; set; }
        public decimal importe { get; set; }
        public byte estado { get; set; }
        public Nullable<byte> tipoPenalizacion { get; set; }
        public string observaciones { get; set; }
        public Nullable<short> codplazaprov { get; set; }
        public Nullable<int> codprov { get; set; }
    }
}
