//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tclientes_red
    {
        public int codcli { get; set; }
        public short codplaza { get; set; }
        public short estado { get; set; }
        public string nombre { get; set; }
        public string direc1 { get; set; }
        public string direc2 { get; set; }
        public string depto { get; set; }
        public string codpos { get; set; }
        public string poblac { get; set; }
        public string provin { get; set; }
        public Nullable<System.DateTime> falta { get; set; }
        public string tlfno { get; set; }
        public string tlfno2 { get; set; }
        public string fax { get; set; }
        public string tarifa { get; set; }
        public string cif { get; set; }
        public Nullable<short> codpago { get; set; }
        public string contact { get; set; }
        public Nullable<double> descuen { get; set; }
        public string banco { get; set; }
        public string agencia { get; set; }
        public string dirbanco { get; set; }
        public string cuenta { get; set; }
        public Nullable<short> vcto { get; set; }
        public string inab { get; set; }
        public string ccfact { get; set; }
        public string coanual { get; set; }
        public Nullable<System.DateTime> f_contr { get; set; }
        public Nullable<short> codcomer { get; set; }
        public string tipocuot { get; set; }
        public Nullable<double> dtocuota { get; set; }
        public string tipocli { get; set; }
        public string tipocliv { get; set; }
        public string faar { get; set; }
        public Nullable<double> cfar { get; set; }
        public string dima { get; set; }
        public Nullable<double> fmax { get; set; }
        public string incr { get; set; }
        public string zona { get; set; }
        public string zon2 { get; set; }
        public string dele { get; set; }
        public string geog { get; set; }
        public string sect { get; set; }
        public string cman { get; set; }
        public string indi { get; set; }
        public Nullable<double> segu { get; set; }
        public string fpre { get; set; }
        public string flre { get; set; }
        public Nullable<double> d1re { get; set; }
        public Nullable<double> d2re { get; set; }
        public string coba { get; set; }
        public string coag { get; set; }
        public string dict { get; set; }
        public Nullable<double> ctar { get; set; }
        public Nullable<double> copr { get; set; }
        public string dest { get; set; }
        public Nullable<double> dtme { get; set; }
        public string inrl { get; set; }
        public Nullable<System.DateTime> fecc { get; set; }
        public string mocc { get; set; }
        public string indp { get; set; }
        public string iniv { get; set; }
        public Nullable<double> reca { get; set; }
        public string rpmo { get; set; }
        public string conf { get; set; }
        public Nullable<double> setr { get; set; }
        public Nullable<double> mist { get; set; }
        public Nullable<double> sem1 { get; set; }
        public Nullable<double> sem2 { get; set; }
        public Nullable<double> mis1 { get; set; }
        public Nullable<double> mis2 { get; set; }
        public string inmo { get; set; }
        public string lial { get; set; }
        public Nullable<double> cfse { get; set; }
        public string attf { get; set; }
        public string copu { get; set; }
        public string faco { get; set; }
        public Nullable<double> dtmf { get; set; }
        public Nullable<short> tise { get; set; }
        public Nullable<double> rieg { get; set; }
        public Nullable<short> codservicio { get; set; }
        public Nullable<short> coddiaPago { get; set; }
        public Nullable<short> codpais { get; set; }
        public string comentarios { get; set; }
        public string mailfact { get; set; }
        public Nullable<byte> modofact { get; set; }
    }
}
