//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class texpdetalle
    {
        public short codplaza_org { get; set; }
        public int codexp { get; set; }
        public System.DateTime f_anota { get; set; }
        public short sec { get; set; }
        public short codplaza_ano { get; set; }
        public short codplaza_dst { get; set; }
        public short codplaza_pag { get; set; }
        public short codmotivo { get; set; }
        public Nullable<short> codplaza_cli { get; set; }
        public Nullable<int> codcli { get; set; }
        public Nullable<int> codcli_may { get; set; }
        public int codcli_red_pag { get; set; }
        public Nullable<int> codprov_red_org { get; set; }
        public Nullable<int> codprov_red_dst { get; set; }
        public short nexp { get; set; }
        public decimal vol { get; set; }
        public Nullable<decimal> kgs { get; set; }
        public short bultos_ini { get; set; }
        public short bultos { get; set; }
        public Nullable<decimal> kgsvol_prv_red_org { get; set; }
        public Nullable<decimal> kgsvol_prv_red_dst { get; set; }
        public Nullable<decimal> kgsvol_cli_red_ini { get; set; }
        public Nullable<decimal> kgsvol_cli_red { get; set; }
        public Nullable<decimal> kgsvol_cli_ini { get; set; }
        public Nullable<decimal> kgsvol_cli { get; set; }
        public Nullable<decimal> kgsvol_prv { get; set; }
        public string ultimo { get; set; }
        public Nullable<int> codcli_fac { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<short> codplaza_prv { get; set; }
        public Nullable<int> codprov { get; set; }
        public string UsuarioAnota { get; set; }
    }
}
