//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TExpDetalle2
    {
        public short Codplaza_org { get; set; }
        public int codexp { get; set; }
        public System.DateTime f_anota { get; set; }
        public string ultimo { get; set; }
        public bool AlbaranCliente { get; set; }
        public string retorno { get; set; }
        public string tfno_cnt { get; set; }
        public string pers_cnt { get; set; }
        public Nullable<System.DateTime> FPEntrega { get; set; }
        public string att_dst { get; set; }
        public string movil_dst { get; set; }
        public string dmail_dst { get; set; }
        public Nullable<short> est_mail { get; set; }
        public Nullable<System.DateTime> fecha_mail { get; set; }
        public string email_remite { get; set; }
        public Nullable<long> CodDestinatario { get; set; }
        public Nullable<short> anulable { get; set; }
        public Nullable<short> est_movil { get; set; }
        public Nullable<System.DateTime> FPEntrega2 { get; set; }
        public Nullable<byte> dninom { get; set; }
        public string gestori { get; set; }
        public string gestdes { get; set; }
    }
}
