//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class texpestado
    {
        public short codplaza_org { get; set; }
        public int codexp { get; set; }
        public System.DateTime fecha { get; set; }
        public short sec { get; set; }
        public short codestado { get; set; }
        public short codplaza_ano { get; set; }
        public int codusuario_ano { get; set; }
        public string ultimo { get; set; }
        public string culpable { get; set; }
        public string parcial { get; set; }
        public string informacion { get; set; }
        public Nullable<short> codincidencia { get; set; }
        public Nullable<System.DateTime> fecha_inc { get; set; }
        public Nullable<short> bultos { get; set; }
        public string cambiapor { get; set; }
        public string UsuarioAnota { get; set; }
    }
}
