//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class texp_codbar_cli
    {
        public short codplaza_org { get; set; }
        public int codexp { get; set; }
        public string codbar { get; set; }
        public string AlbAgrupacion { get; set; }
        public string AlbAgrupacionDst { get; set; }
        public System.Guid UidExp { get; set; }
        public string codbar_ENV { get; set; }
        public string codbarras_retorno { get; set; }
    }
}
