//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPdaPosiciones
    {
        public long id { get; set; }
        public Nullable<long> codplaza_rep { get; set; }
        public Nullable<long> codrepartidor { get; set; }
        public Nullable<short> tipo { get; set; }
        public Nullable<long> codplaza_org { get; set; }
        public Nullable<long> codexp { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
        public Nullable<System.DateTime> fpda { get; set; }
        public System.DateTime fabd { get; set; }
        public string status { get; set; }
        public string polyLine { get; set; }
        public Nullable<double> boundSWLat { get; set; }
        public Nullable<double> boundSWLng { get; set; }
        public Nullable<double> boundNELat { get; set; }
        public Nullable<double> boundNELng { get; set; }
        public Nullable<double> distancia { get; set; }
        public Nullable<double> duracion { get; set; }
        public Nullable<long> idorg { get; set; }
        public Nullable<System.DateTime> fstatus { get; set; }
        public Nullable<System.DateTime> fgps { get; set; }
    }
}
