//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tplazas
    {
        public short codplaza { get; set; }
        public string plaza { get; set; }
        public string nemonico { get; set; }
        public int codcli_red { get; set; }
        public int codprov_red { get; set; }
        public Nullable<short> codplaza_old { get; set; }
        public short plz_internacional { get; set; }
        public string operativa { get; set; }
        public string reparto { get; set; }
        public short codprovincia { get; set; }
        public short codregion { get; set; }
        public short bpack { get; set; }
        public string mail { get; set; }
        public Nullable<short> codzona { get; set; }
        public Nullable<short> codpais { get; set; }
        public string CpNave { get; set; }
        public string NombreWEB { get; set; }
        public string NombreComercial { get; set; }
        public string Direccion { get; set; }
        public string Poblacion { get; set; }
        public string Provincia { get; set; }
        public string Cp { get; set; }
        public string Gerente { get; set; }
        public string Responsable { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string MailWeb { get; set; }
        public string MailComercial { get; set; }
        public string MailOperativo { get; set; }
        public string hoficina { get; set; }
        public short visibleWeb { get; set; }
        public short Software { get; set; }
        public Nullable<System.DateTime> FSoftWare { get; set; }
        public Nullable<long> codPunto { get; set; }
        public string logistica { get; set; }
        public string DireccionWeb { get; set; }
        public Nullable<short> codIsla { get; set; }
        public Nullable<short> tipoplaza { get; set; }
    }
}
