//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tRepartoHojas
    {
        public int hoja { get; set; }
        public System.DateTime fecha { get; set; }
        public int codrepartidor { get; set; }
        public Nullable<System.DateTime> fecha_liquidacion { get; set; }
        public Nullable<int> nenvios { get; set; }
        public Nullable<short> estado { get; set; }
        public Nullable<System.DateTime> fecha_cierre { get; set; }
        public short codplaza { get; set; }
        public Nullable<short> codplaza_rep { get; set; }
        public Nullable<System.DateTime> ftick { get; set; }
    }
}
