//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trepartidores
    {
        public short codplaza { get; set; }
        public int codrepartidor { get; set; }
        public string repartidor { get; set; }
        public string tipo { get; set; }
        public string direccion { get; set; }
        public string cp { get; set; }
        public string localidad { get; set; }
        public string provincia { get; set; }
        public Nullable<System.DateTime> fechaalta { get; set; }
        public string tlfno { get; set; }
        public string fax { get; set; }
        public Nullable<short> codtarifa { get; set; }
        public string cif { get; set; }
        public Nullable<short> codvehiculo { get; set; }
        public string numlocalizador { get; set; }
        public Nullable<short> codtipoprov { get; set; }
        public Nullable<System.DateTime> fechabaja { get; set; }
        public short codCola { get; set; }
        public Nullable<bool> repartePuntoDia { get; set; }
    }
}
