//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tReparto
    {
        public short codplaza_org { get; set; }
        public int codexp { get; set; }
        public Nullable<int> hoja { get; set; }
        public Nullable<int> hojaAut { get; set; }
        public Nullable<int> hojaMan { get; set; }
        public Nullable<short> codservicio { get; set; }
        public System.DateTime fecha { get; set; }
        public string calle_dst { get; set; }
        public string localidad_dst { get; set; }
        public string nombre_dst { get; set; }
        public string cp_dst { get; set; }
        public string referencia { get; set; }
        public Nullable<decimal> reembolso { get; set; }
        public Nullable<decimal> debidos { get; set; }
        public Nullable<short> bultos { get; set; }
        public Nullable<decimal> kgs { get; set; }
        public short escaneo { get; set; }
        public short liquidacion { get; set; }
        public Nullable<System.DateTime> fecha_liquidacion { get; set; }
        public System.DateTime fecha_asignacion { get; set; }
        public Nullable<int> codrepartidor { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<short> tipo { get; set; }
        public Nullable<short> ppago { get; set; }
        public Nullable<short> codplaza { get; set; }
    }
}
