//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tslrEstados
    {
        public long id { get; set; }
        public long CodRecogida { get; set; }
        public System.DateTime f_tick { get; set; }
        public string Ultimo { get; set; }
        public System.DateTime f_estado { get; set; }
        public short CodEstado { get; set; }
        public Nullable<short> CodPlaza_ano { get; set; }
        public Nullable<System.Guid> CodUsuario { get; set; }
        public string Observacion { get; set; }
    }
}
