//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tslrExpediciones
    {
        public short Codplaza_Org { get; set; }
        public int codexp { get; set; }
        public long CodRecogida { get; set; }
        public Nullable<System.DateTime> f_tick { get; set; }
        public Nullable<long> sec_dst { get; set; }
    }
}
