//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tslrRecogidas
    {
        public long CodRecogida { get; set; }
        public short CodPlaza_sol { get; set; }
        public short CodPlaza_org { get; set; }
        public System.DateTime FSolicitud { get; set; }
        public System.DateTime FRecogida { get; set; }
        public Nullable<System.DateTime> HDesde1 { get; set; }
        public Nullable<System.DateTime> HHasta1 { get; set; }
        public Nullable<System.DateTime> HDesde2 { get; set; }
        public Nullable<System.DateTime> HHasta2 { get; set; }
        public int Codcli { get; set; }
        public int CodcliRed { get; set; }
        public string NombSol { get; set; }
        public string NombRec { get; set; }
        public string DirRec { get; set; }
        public string PoblRec { get; set; }
        public string cpRec { get; set; }
        public string ContacRec { get; set; }
        public string TfnoRec { get; set; }
        public string DptoRec { get; set; }
        public Nullable<short> vehiculo { get; set; }
        public string ObsRec { get; set; }
        public decimal CodSolicitud_ant { get; set; }
        public Nullable<short> codpais_org { get; set; }
        public Nullable<short> codprovincia_org { get; set; }
        public bool transPDA { get; set; }
        public bool Ayudante { get; set; }
        public bool Klms { get; set; }
        public string tipo { get; set; }
        public Nullable<short> via { get; set; }
        public Nullable<int> CodFija { get; set; }
        public string Pre_conf { get; set; }
        public string movilRec { get; set; }
        public string dmailRec { get; set; }
        public Nullable<short> est_mail { get; set; }
        public Nullable<bool> dac { get; set; }
        public Nullable<bool> PD { get; set; }
        public Nullable<bool> Reem { get; set; }
        public Nullable<short> Retorno { get; set; }
        public Nullable<byte> dninom { get; set; }
        public string gestori { get; set; }
    }
}
