//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class webContactosTracking
    {
        public long id { get; set; }
        public long idContacto { get; set; }
        public short tipo { get; set; }
        public string texto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<short> codplaza_ano { get; set; }
        public string usuario { get; set; }
    }
}
