//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class webContactos
    {
        public long id { get; set; }
        public System.DateTime fecha { get; set; }
        public string empresa { get; set; }
        public string contacto { get; set; }
        public string direccion { get; set; }
        public string poblacion { get; set; }
        public string cp { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string peticion { get; set; }
        public string texto { get; set; }
        public Nullable<short> codplaza { get; set; }
        public byte estado { get; set; }
    }
}
