//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASM.BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clReclamaciones
    {
        public long id { get; set; }
        public Nullable<byte> tipoReclamacion { get; set; }
        public Nullable<short> codplazaReclama { get; set; }
        public Nullable<short> codplazaReclamada { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public Nullable<int> codexp { get; set; }
        public Nullable<long> codrecogida { get; set; }
        public Nullable<decimal> importePenalizacion { get; set; }
        public Nullable<decimal> importeIndemnizacion { get; set; }
        public Nullable<short> codplazaPenalizada { get; set; }
        public Nullable<short> codplazaIndemnizada { get; set; }
    }
}
